### PR TITLE
VSOCK: fix reaper timeout

### LINKED ISSUE #112: libkrun is leaking TCP sockets
I am trying to run an [avalanchego 1.9.7](https://github.com/ava-labs/avalanchego/releases/tag/v1.9.7) node in an AMD SEV-ES TEE.
The app in question is a non-validating node in the Avalanche (P2P) network. Anybody can run this without investing in Avalanche. Avalanche nodes "discover" each over TCP port 9650 (in my case 9750). A node typically connects to 1000+ other nodes (I had to bump the NOFILE limit to 32768 - both for the VMM and in the guest TEE). 

My node seems to be working well for about 24 hours - the only thing off is:

1. every 20-30 the HTTP request (e.g. the [health api](https://docs.avax.network/apis/avalanchego/apis/health)) is delayed 10-45 seconds
2. there are frequent (seconds) `deferring proxy removal` warnings in libkrun logs
3. occasional (minutes) `stream: unhandled op` warnings with VSOCK_OP_RST 

After approx 24h. I can no longer reach my node over HTTP:
- I can see the thousands of TCP sockets in state `CLOSE-WAIT`.
- In libkrun logs this shows up frequently now: ` ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq`
- I can no longer connect to my TEE app over e.g. HTTP (not even SYN goes through to libkrun)

**The libkrun host system**
- AMD EPYC 7302P (SEV FW: 0.24 build 17)
- (up-to-date) debian bullseye backports kernel: `6.0.12-1~bpo11+1`

**The guest system**
- libkrun 1.4.9
- libkrunfw 3.9.0

<hr/>

Socket status on libkrun host:

```shell
ss -sp --tcp state CLOSE-WAIT
Total: 8294
TCP:   11475 (estab 1122, closed 5650, orphaned 0, timewait 5)

Transport Total     IP        IPv6
RAW       0         0         0        
UDP       1         1         0        
TCP       5825      5824      1        
INET      5826      5825      1        
FRAG      0         0         0        

Recv-Q Send-Q Local Address:Port     Peer Address:Port Process                                   
293    0          127.0.0.1:9750        127.0.0.1:40636 users:(("libkrun VM",pid=245580,fd=5493))
293    0          127.0.0.1:9750        127.0.0.1:33738 users:(("libkrun VM",pid=245580,fd=5756))
293    0          127.0.0.1:9750        127.0.0.1:36756 users:(("libkrun VM",pid=245580,fd=2101))
293    0          127.0.0.1:9750        127.0.0.1:56618 users:(("libkrun VM",pid=245580,fd=1872))
293    0          127.0.0.1:9750        127.0.0.1:51638 users:(("libkrun VM",pid=245580,fd=3849))
293    0          127.0.0.1:9750        127.0.0.1:42248 users:(("libkrun VM",pid=245580,fd=6794))
...
```

libkrun logs when avalanchego is no longer reachable on HTTP:

```shell
[2023-01-28T13:40:15Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:16Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:17Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:18Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:18Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
```

Socket leak rate over time:

image

### PR DESCRIPTION
**Pull request by blenessy**
This fixes #112 ...

This fixes recv_timeout so that it blocks:
1. until the next event arrives (Duration.MAX)
2. until next socket can be closed (<5s)

Please don't ask me to explain the exact relation between this fix and the socket leak in #112 :)  - I do not have enough understanding for KVM Host-Guest networking works. All I know is that this fixes a valid bug in reaper and after that I can no longer reproduce #112.

In regards to testing I  have this patch with the scenario in #112 for ~6 days.
And you can clearly see that the `TCP_inuse` no longer grows proportionally with `TCP_alloc` metric:
image

### CODE REVIEW

**Comment by blenessy** [comment]
Clippy is failing in `rc/devices/src/virtio/queue.rs` ... I did not touch this file ...

**Comment by slp** [comment]
> Clippy is failing in `rc/devices/src/virtio/queue.rs` ... I did not touch this file ...

Don't worry about this, CI's clippy has updated and started complaining about something it didn't complain before (happens quite a while).

On the other hand, your patch looks correct to me and fixes the behavior of the reaper, though I'm not sure how this fixes the socket leak. In any case, I think it should be merged. Thanks!

**Review by slp — APPROVED** [review]

**Comment by slp** [comment]
@blenessy Could you please rebase on top of main to fix the CI warnings

**Comment by blenessy** [comment]
> @blenessy Could you please rebase on top of main to fix the CI warnings

Done @slp !

**Review by slp — APPROVED** [review]

**Pull request merged**
