### PR TITLE
virtio/fs/macos: fix submounts

### PR DESCRIPTION
**Pull request by slp**
Fix submount navigation by decoupling host<->guest inode numbers and implementing support for FUSE SUBMOUNTS, based on virtiofsd implementation.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@jakecorrenti  @tylerfanelli PTAL

**Review by tylerfanelli — APPROVED** [review]
LGTM

**Comment by jakecorrenti** [comment]
LGTM as well

**Pull request merged**
