### PR TITLE
Update SEV deps to latest versions

### PR DESCRIPTION
**Pull request by slp**

### CODE REVIEW

**Comment by slp** [comment]
@tylerfanelli PTAL

**Review by tylerfanelli — APPROVED** [review]
LGTM, but the sev crate's 4.0.0 will not run on upstream kernels. We're looking to update to 5.0.0 now that 6.11 brought "stable" support. Perhaps we should wait to update libkrun until sev-5.0.0 is up? Shouldn't be much longer

**Comment by slp** [comment]
> LGTM, but the sev crate's 4.0.0 will not run on upstream kernels. We're looking to update to 5.0.0 now that 6.11 brought "stable" support. Perhaps we should wait to update libkrun until sev-5.0.0 is up? Shouldn't be much longer

We need it to be in sync with the status of the packages in Fedora to be able to produce new releases. We can do another omnibus updates once 5.0.0 is released.

**Comment by tylerfanelli** [comment]
SGTM.

**Pull request merged**
