### PR TITLE
Bump version to v1.4.9

### PR DESCRIPTION
**Pull request by slp**
This release includes initial SNP support and a fix when parsing environment variables in init.c, bump release number to v1.4.9.

Signed-off-by: Sergio Lopez <slp@redhat.com>

### CODE REVIEW

**Comment by tylerfanelli** [comment]
@slp I see that your still pushing changes. Is this ready for review?

**Comment by slp** [comment]
@tylerfanelli Sorry, it's close, but I'm still testing it under macOS, as the clippy fix commit touches common files.

**Comment by slp** [comment]
@tylerfanelli Now it's ready :-)

**Review by tylerfanelli — APPROVED** [review]

**Comment by tylerfanelli** [comment]
@slp Merged :)

**Pull request merged**
